#!/bin/bash

nasm boot.asm -o boot.bin
nasm loader.asm -o loader.bin

dd if=boot.bin of=boot.img bs=512 count=1 conv=notrunc
sudo mount -o loop boot.img /mnt/floppy
sudo cp loader.bin /mnt/floppy/ -v


