#ifndef	VIOS_CONFIG_H
#define	VIOS_CONFIG_H

#define	MINOR_BOOT		MINOR_HD2A

#define	ENABLE_DISK_LOG
#define	SET_LOG_SECT_SMAP_AT_STARTUP
#define	MEMSET_LOG_SECTS
#define	NR_SECTS_FOR_LOG		NR_DEFAULT_FILE_SECTS

#endif