#ifndef	VIOS_CONFIG_H
#define	VIOS_CONFIG_H

#define	MINOR_BOOT		MINOR_HD2A

#define	BOOT_PARAM_ADDR		0x900
#define	BOOT_PARAM_MAGIC		0xB007
#define	BI_MAGIC				0
#define	BI_MEM_SIZE			1
#define	BI_KERNEL_BIN		2

#define	INSTALL_START_SECT	0x8000
#define	INSTALL_NR_SECTS	0x800

#define	ENABLE_DISK_LOG
#define	SET_LOG_SECT_SMAP_AT_STARTUP
#define	MEMSET_LOG_SECTS
#define	NR_SECTS_FOR_LOG		NR_DEFAULT_FILE_SECTS

#endif